services:
  - type: web
    name: go-archive-pgc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    envVars:
      - key: EVENT
        value: pgc
      - key: NODE_VERSION
        value: "24"

  - type: web
    name: go-archive-wagc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    envVars:
      - key: EVENT
        value: wagc
      - key: NODE_VERSION
        value: "24"

  - type: web
    name: go-archive-pwgc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    envVars:
      - key: EVENT
        value: pwgc
      - key: NODE_VERSION
        value: "24"

  - type: web
    name: go-archive-pagc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    envVars:
      - key: EVENT
        value: pagc
      - key: NODE_VERSION
        value: "24"

  - type: web
    name: go-archive-pygc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    envVars:
      - key: EVENT
        value: pygc
      - key: NODE_VERSION
        value: "24"
