services:
  - type: web
    name: go-archive-wagc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    buildFilter:
      paths:
        - configurations/wagc.yml
        - events/wagc/**
        - src/**
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    domains:
      - wagc.go.art.pl
    envVars:
      - key: CONFIG
        value: wagc
      - key: NODE_VERSION
        value: '24'

  - type: web
    name: go-archive-pwgc
    runtime: static
    branch: main
    buildCommand: npm ci && npm run build
    buildFilter:
      paths:
        - configurations/pwgc.yml
        - events/pwgc/**
        - src/**
    staticPublishPath: ./out
    previews:
      generation: manual
    autoDeployTrigger: checksPass
    domains:
      - mpk.go.art.pl
    envVars:
      - key: CONFIG
        value: pwgc
      - key: NODE_VERSION
        value: '24'
