name: Build From Configuration

on:
  workflow_call:
    inputs:
      config:
        description: Configuration name
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.config }}
    runs-on: ubuntu-latest
    env:
      CONFIG: ${{ inputs.config }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CONFIG }}
          path: out/
          if-no-files-found: error
          compression-level: 6
