name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      config:
        description: Configuration name
        required: true
        default: europe
        type: string

jobs:
  build-defaults:
    if: github.event_name == 'push'
    name: Build ${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - europe
    uses: ./.github/workflows/_build-from-config.yml
    with:
      config: ${{ matrix.config }}

  build-manual:
    if: github.event_name == 'workflow_dispatch'
    name: Build ${{ inputs.config }}
    uses: ./.github/workflows/_build-from-config.yml
    with:
      config: ${{ inputs.config }}
