name: Deploy

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      event:
        description: Event
        required: true
        type: choice
        default: pgc
        options:
          - pgc
          - pygc

jobs:
  deploy-pgc-prod:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.event == 'pgc' }}
    runs-on: ubuntu-latest
    environment: pgc
    env:
      EVENT: pgc
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run build

      - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ vars.PGC_FTP_HOST }}
          username: ${{ secrets.PGC_FTP_USER }}
          password: ${{ secrets.PGC_FTP_PASS }}
          local-dir: ./out/
          server-dir: ${{ vars.PGC_FTP_PATH }}

  deploy-pygc-prod:
    if: ${{ github.event_name == 'pull_request' || inputs.event == 'pygc' }}
    runs-on: ubuntu-latest
    environment: pygc
    env:
      EVENT: pygc
      SSH_PATH: "/usr/home/${{ secrets.PYGC_SSH_USER }}/domains/${{ vars.SSH_HOST }}/public_nodejs/archive"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci

      - run: npm run build

      - name: Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASS }}
          source: out/*
          strip_components: 1
          target: ${{ env.SSH_PATH }}
