name: Deploy pgc
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  VERSION: ${{ github.sha }}
jobs:
  deploy-pgc-prod:
    runs-on: ubuntu-latest
    environment:
      name: pgc
      url: ${{ vars.SITE }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy archive
        uses: ./.github/actions/deploy-ftp
        with:
          config: pgc
          ftp-host: ${{ vars.FTP_HOST }}
          ftp-path: public_html/${{ vars.FTP_HOST }}/archive
          site-url: ${{ vars.SITE }}
        env:
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_TOKEN: ${{ secrets.FTP_TOKEN }}
